  obstacle_range: 6.0
  raytrace_range: 7.0
  footprint: [[-0.05,-0.13],[-0.05,0.13],[0.3, 0.13],[0.4, 0],[0.3,-0.13]]
  robot_radius: 0.25
  inflation_radius: 0.25
  max_obstacle_height: 0.40
  min_obstacle_height: 0.03
  observation_sources: scan 

  scan: {sensor_frame: base_link,  observation_persistence: 0.0, 
  max_obstacle_height: 0.3, min_obstacle_height: 0.05, data_type: LaserScan, topic: /scan, 
  marking: true,clearing: true}


